"""Instantly API v2 client — minimal, focused on the cold email use case.

Why we use Instantly and not raw SMTP:
  - Deliverability: warm-up across multiple inboxes, sending limits, DKIM/SPF
    fingerprinting, reputation management — all things you don't want to
    reimplement.
  - Compliance: opt-out link auto-injection, suppression lists, tracking opt-outs.
  - Volume: built for cold outreach, not transactional mail.

What we do here:
  - POST /api/v2/leads to add a personalized lead to a campaign
  - Each lead carries `personalization` (= custom variables) used by the campaign
    template: {{first_name}}, {{personalization.subject}}, {{personalization.body_html}}
  - The campaign's email sequence body in Instantly UI should be:
      Subject: {{personalization.subject}}
      Body:    {{personalization.body_html}}
    — that way our per-prospect generated content flows through.

References:
  - Auth: https://developer.instantly.ai/getting-started
  - Leads: https://developer.instantly.ai/api/v2/lead/create-lead
"""

from __future__ import annotations

from dataclasses import dataclass

import httpx

from .config import CONFIG


class InstantlyError(RuntimeError):
    """Raised on any non-200 response or auth failure."""


@dataclass
class InstantlyLeadResult:
    lead_id: str
    raw_response: dict


def _headers() -> dict:
    if not CONFIG.instantly_api_key:
        raise InstantlyError(
            "INSTANTLY_API_KEY missing. Get one at https://app.instantly.ai/settings/integrations"
        )
    return {
        "Authorization": f"Bearer {CONFIG.instantly_api_key}",
        "Content-Type": "application/json",
    }


def add_lead_to_campaign(
    *,
    campaign_id: str,
    email: str,
    company_name: str,
    first_name: str = "",
    last_name: str = "",
    personalization: dict | None = None,
    timeout: float = 30.0,
) -> InstantlyLeadResult:
    """Create a lead in Instantly and assign it to the campaign.

    The campaign's email sequence in Instantly's UI should reference
    {{personalization.subject}} and {{personalization.body_html}} for the
    fields generated by EmailAgent.
    """
    if not campaign_id:
        raise InstantlyError("campaign_id is required")
    if not email:
        raise InstantlyError("email is required")

    payload: dict = {
        "campaign": campaign_id,
        "email": email,
        "company_name": company_name,
    }
    if first_name:
        payload["first_name"] = first_name
    if last_name:
        payload["last_name"] = last_name
    if personalization:
        payload["personalization"] = personalization
        # Instantly v2 uses 'custom_variables' in some doc versions; pass both for safety.
        payload["custom_variables"] = personalization

    url = f"{CONFIG.instantly_base_url.rstrip('/')}/leads"

    try:
        with httpx.Client(timeout=timeout) as c:
            r = c.post(url, headers=_headers(), json=payload)
    except httpx.HTTPError as e:
        raise InstantlyError(f"Network error reaching Instantly: {e}") from e

    if r.status_code in (401, 403):
        raise InstantlyError(
            f"Instantly auth failed ({r.status_code}). "
            f"Check INSTANTLY_API_KEY scope. Response: {r.text[:300]}"
        )
    if r.status_code == 404:
        raise InstantlyError(
            f"Campaign not found ({r.status_code}). "
            f"Check INSTANTLY_CAMPAIGN_ID = '{campaign_id}'. Response: {r.text[:300]}"
        )
    if r.status_code == 409:
        # Lead already exists in this campaign
        raise InstantlyError(
            f"Lead already exists in campaign (409): {email}. Skip or use update endpoint."
        )
    if r.status_code >= 400:
        raise InstantlyError(
            f"Instantly returned {r.status_code}: {r.text[:500]}"
        )

    data = r.json()
    # API returns { "id": "..." } at top level (sometimes wrapped in { "data": ... })
    lead_id = data.get("id") or data.get("data", {}).get("id") or ""
    return InstantlyLeadResult(lead_id=str(lead_id), raw_response=data)


# --- Pre-flight check ------------------------------------------------------

def preflight() -> list[str]:
    """Return list of issues. Empty list = ready to send."""
    issues: list[str] = []
    if not CONFIG.instantly_api_key:
        issues.append("INSTANTLY_API_KEY missing in .env")
    if not CONFIG.instantly_campaign_id:
        issues.append("INSTANTLY_CAMPAIGN_ID missing in .env")
    if not CONFIG.sender_name or not CONFIG.sender_company:
        issues.append("SENDER_NAME and SENDER_COMPANY required for RGPD mentions légales")
    if not CONFIG.sender_siren:
        issues.append("SENDER_SIREN required for RGPD mentions légales")
    if not CONFIG.sender_address:
        issues.append("SENDER_ADDRESS required for RGPD mentions légales")
    if not CONFIG.sender_reply_to:
        issues.append("SENDER_REPLY_TO required (where replies arrive)")
    return issues
